name: CI for nuxt.js pr Command testing

on:
  # issue_comment:
  #   types: [created]
  push:
    branches:
      - "*"
      - "*/*"
      - "**"
    paths:
      - "**.spec.ts"

jobs:
  test:
    # if: contains(github.event.comment.body, 'run tests')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci
      # - name: Install dependencies
      # run: yarn install
      # run: yarn install --frozen-lockfile

      # https://github.com/marketplace/actions/changed-files
      # 변경된 파일만 추출 하는 uses
      - name: Get Cahange Files
        id: changed_files
        uses: tj-actions/changed-files@v37
        with:
          files: |
            **.spec.ts

      - name: Run tests on changed files
        run: |
          echo "Running tests for: {{$steps.changed_files.outputs.all_changed_files }}"
          npm run test:verbose ${{steps.changed_files.outputs.all_changed_files }}

# git diff --name-only --diff-filter=M dev | grep '\.spec.ts$' | tr '\n' ' '
